---
title: "Variables in CenSoc"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Below is a list of variables contained in the CenSoc data set. 

# CenSoc Variables

- `HISTID` consistent individual-level identifier
- `STATEFIP` reports the state in which a household was located
- `census_age` refers to the individual's age at the time of the 1940 Census. 
- `byear`: year of birth
- `dyear`: year of death
- `bmonth`: month of birth
- `dmonth`: month of death

# CenSoc (SS-5) Variables

- `HISTID` consistent individual-level identifier
- `census_age` refers to the individual's age at the time of the 1940 Census. 
- `byear`: year of birth
- `dyear`: year of death
- `bmonth`: month of birth
- `dmonth`: month of death
- `dstate` state of death (from death record)
- `socstate` state where social security number was issued

# 1940 Census Variables

Below are examples of select variables available in the 1940 census available on the [IPUMS-USA](https://usa.ipums.org/usa/) website.

- `SERIAL40`: Household serial number in 1940 Census
- `NUMPREC40`: Number of person records in household
- `PERNUM`: Person number within household
- `STATEFIP`: State of residence FIPS code
- `URBAN`: Lives in urban or rural area
- `OWNERSHP`: Owns or rents dwelling
- `RENT`: Monthly rent
- `RACE`: race
- `HISPAN`: Hispanic status
- `MARST`: marital status
- `EDUC`: Education
- `BPL`: Place of birth
- `MBPL`: Mother's place of birth
- `FBPL`: Father's place of birth
- `EMPSTAT`: Employment status
- `OCCSCORE`: Occupational income score
- `OCC`: Occupation
- `INCWAGE`: Income from wages
- `INCNONWG`: Has non-wage income greater than $50

For full documentation about the census variables, refer to the IPUMS website: [https://usa.ipums.org/usa-action/variables/search](https://usa.ipums.org/usa-action/variables/search).

